# Generated by Django 3.2.6 on 2021-08-25 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_num', models.CharField(max_length=30)),
                ('bank', models.CharField(max_length=20)),
                ('balance', models.IntegerField(null=True)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='bankAccount', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
