# Generated by Django 3.2.6 on 2021-08-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='income',
            field=models.IntegerField(null=True),
        ),
    ]
