# Generated by Django 3.2.6 on 2021-08-28 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='consum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('category', models.CharField(blank=True, choices=[('식비', '식비'), ('교통비', '교통비'), ('카페&간식', '카페&간식'), ('편의점&마트', '편의점&마트'), ('쇼핑', '쇼핑'), ('술&유흥', '술&유흥'), ('의료비', '의료비'), ('공과금', '공과금'), ('기타', '기타')], max_length=10, null=True)),
                ('money', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
