# Generated by Django 3.2.6 on 2021-08-29 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_bankaccount_name'),
        ('accounting', '0002_testinfomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioninfo',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.bankaccount'),
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
